import './globals.css'
import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Provider from '@/context/Provider'
import { SessionProvider } from 'next-auth/react'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>
          <div className="flex flex-col">
            <Link href="/">Home</Link>
            <Link href="/api/auth/signout">Logout</Link>
            {children}
          </div>
        </body>
      </Provider>
    </html>
  )
}
